In [3]:
print('hi')

hi


In [9]:
s = 'a sample python step'

In [14]:
s[-6:-12:-1]
s[::-1]

'pets nohtyp elpmas a'

In [15]:
d1 = [{'a:34'},66,{'66':[{'00':[98,'hi']},'awesome',{'m':'n'}]}]


In [16]:
d1[2]['66'][0]['00'][0]

98

In [17]:
s = '468hi3.4' #str
a = [4,6,8,'hi',3.4] #list
b = (4,6,8,'hi',3.4) #tuple
c = {4:6,8:['hi',3.4]} #dict
d = {4,6,8,'hi',3.4} #set

In [18]:
type(s),type(a),type(b),type(c),type(d)

(str, list, tuple, dict, set)

In [19]:
len(s),len(a),len(b),len(c),len(d)

(8, 5, 5, 2, 5)

In [21]:
'hi' + 'hello' # by using '+' between two strings , the string concatenates

'hihello'

In [22]:
[4,5] + [3,6] 

[4, 5, 3, 6]

In [24]:
(4,5) + (5,6)

(4, 5, 5, 6)

In [23]:
{4,5} + {3,6} # concatenation by + is not possible for set and dict

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [25]:
'hi' * 3 # by using * , string repeats

'hihihi'

In [28]:
s+= 'k'
s    # by using + we can recreate the string and can do some change in the string.

'468hi3.4kkk'

In [34]:
s = '468hi3.4'
s

'468hi3.4'

In [35]:
s[:3]

'468'

In [36]:
s[3:]

'hi3.4'

In [37]:
s = s[:3] + 'hello' + s[3:]
s

'468hellohi3.4'

In [47]:
a += ["Bye"]
a

[4,
 6,
 8,
 'hi',
 3.4,
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye']

In [49]:
a = a[:2] + [39] + a[2:]
a

[4,
 6,
 39,
 8,
 'hi',
 3.4,
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye']

In [55]:
b += tuple('bye')
b

(4, 6, 8, 'hi', 3.4, 'b', 'y', 'e')

In [56]:
b += ('bye',) # we have to add comma, at last for adding something in tuple
b

(4, 6, 8, 'hi', 3.4, 'b', 'y', 'e', 'bye')

In [60]:
(*b,*b)

(4,
 6,
 8,
 'hi',
 3.4,
 'b',
 'y',
 'e',
 'bye',
 4,
 6,
 8,
 'hi',
 3.4,
 'b',
 'y',
 'e',
 'bye')

In [ ]:
#by using asterisk we can join a list and a tuple and a string also  and it will return the output in the form of tuple

(*a,*b,*s)

In [65]:
c

{4: 6, 8: ['hi', 3.4]}

In [66]:
c[99] = [86,'ekValue'] # by this we can add new key value pair in dict
c

{4: 6, 8: ['hi', 3.4], 99: [86, 'ekValue']}

In [67]:
c2 = {'a':4,"b":35}
c2

{'a': 4, 'b': 35}

In [68]:
{**c,**c2}  # two dict can be joined by using asterisk

{4: 6, 8: ['hi', 3.4], 99: [86, 'ekValue'], 'a': 4, 'b': 35}

In [69]:
s

'468hellohi3.4'

In [70]:
s[0] = 'a' # since string is immutable

TypeError: 'str' object does not support item assignment

In [72]:
a[0] ='a' # list is mutable , so it changes
a

['a',
 6,
 39,
 8,
 'hi',
 3.4,
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye',
 'Bye']

In [ ]:
## Item Assignment
# s[0]= "a" --> not possible
# a[0]= "a" --> possible
# b[0]= "a" --> not possible
# c[4]= 66 --> possible

## Item Deletion
# del s[0] --> not possible
# del a[0] -->  possible
# del b[0] --> not possible
# del c[0] -->  possible

In [75]:
print(bool(' ')),bool([]),bool({}),bool(()),bool(-1),bool(45),bool([()])


True


(None, False, False, False, True, True, True)

In [78]:
p = 34
q = 34.5
r = 34+5j
t = 'hello'
e = [3,4,5]
f = (3,4,5)
g = {3:[ 4,5]}
h = {3,4,5}

In [83]:
t.upper()

'HELLO'

In [84]:
t = t.upper()
t

'HELLO'

In [86]:
t.find('O')

4

In [87]:
t.strip('OHL')

'E'

In [88]:
'STAR'.join('wars')

'wSTARaSTARrSTARs'

In [89]:
'~'.join('wars')

'w~a~r~s'

In [90]:
'#'.join("hi this is a new string".split())

'hi#this#is#a#new#string'

In [94]:
'hi this is a new string'.replace(' ','#')

'hi#this#is#a#new#string'

In [93]:
t.count('L')

2

In [95]:
## String formatting 
x = 20
y = 30
# z= "ek aisa data jo 20 ko 30 hai"

# (format specifiers)
z = " ek aisa data jo %d to %d hai"%(x,y)
z1 = 'ek aisa data jo %d to %d hai lekin %d hi kaafi hai '%(x,y,x)

# using format function 
z = 'ek aisa data jo {} to {} hai'
z = z.format(x,y)
# z = ' ek aisa data jo {} to {} hai'.format(x,y)
# ek aisa data jo 20 to 30 hai lekij 20 hi kaafi hai
z1 = 'ek aisa data jo {} to {} hai lekin {} hi kaafi hai'
z1.format(x,y,x)

# using f-string
zf = f'ek aisa data jo {x} to {y} hai lekin {x} hi kaafi hai'
zf


'ek aisa data jo 20 to 30 hai lekin 20 hi kaafi hai'

In [96]:
e1 = ['hi','wow','good','hey','awesome']
e1

['hi', 'wow', 'good', 'hey', 'awesome']

In [98]:
e1.sort(key=len)
e1

['hi', 'wow', 'hey', 'good', 'awesome']

In [99]:
e1.sort(key=len,reverse = True)
e1

['awesome', 'good', 'wow', 'hey', 'hi']

In [100]:
f1 = list(f)
f1.sort(reverse = True)
f1 = tuple(f1)
f1

(5, 4, 3)

In [20]:
# identifiers
# keyword
# operators
  # 1. Arithmetic: +,-,*,/,**,//,%
  # 2. Relational: ==,<=,>=,<,>
  # 3. Assignment: =,+=,-=,*=......
  # 4. Logical: and,or,not
  # 5. Membership: in,not in
  # 6. Bitwise: &,|,^,~,<<,>>
  # 7. Identity: is, is not
# Data types / data classes
  # Numeric: int,float,complex
  # Sequences:-
    # str : immutable collection of characters ' '   " "    ''' '''
    # list : mutable and unstructured collection of heterogeneous elements. []
    # tuples : immutable and unstructured collection of heterogeneous elements.() 
    # Mapping :
      # dict : mutable & structured collection of key-value pairs. {} --> the item of dictionary is called as key value pair
      # set : unordered collection of unique items
    # Boolean:- 
      # bool: true,false ( anything non-zero or non-empty is true)
    #  Empty data: 
      # NoneType: none
# Data operations(collections)
    # 1. Item Accessing(Indexing/Slicing/Subscripting)
    # 2. Item Insertion
    # 3. Item Assignment(possible with mutable only)
    # 4. Item Deletion(possible with mutable only)

 # Data tupe built-in functions
   # str: upper,lower,find,split,strip,join,format,count
   # list: append,sort,count,copy,insert,remove,index,pop
   # tuple: count,index
   # dict: keys,values,pop,update,get
   # set: add,difference,union,pop,remove   

# args and kwargs    
    



# in python variable is termed as mutable and constant is termed as immutable.

In [6]:
from keyword import kwlist

In [ ]:
# do-while

while

for(int i=1;i<11;i++){
    Aarshi
}

foreach(int i in somearray){
    do something
}

for-each

for obj in collection:
    pass

range()

In [101]:
list(range(1,1001,1))

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [102]:
a = [4,'hi','nice',35]
b = []
for i in range(len(a)):
    b.append(a[i] * 2)
b    

[8, 'hihi', 'nicenice', 70]

In [103]:
a = [4,'hi','nice',35]
b = []
for val in a:
    b.append(val * 2)
b  

[8, 'hihi', 'nicenice', 70]

In [104]:
a * 2

[4, 'hi', 'nice', 35, 4, 'hi', 'nice', 35]

In [105]:
# Comprehension
## For-loop Statements which are of one liner

# List comprehension
#    [output for-loop]
#    [output for-loop if-condition]
# Dictionary comprehension
#    {key_op:value_op for-loop}
# Set comprehension
#    {output for-loop}
# generator comprehension
#    (output for-loop)
b = [val*2 for val in a]
b

[8, 'hihi', 'nicenice', 70]

In [106]:
k = [4,7,3,67,43,34,2,4,45,22,11,9,8]


In [109]:
p = [val for val in k if val % 2 ==0]
p


[4, 34, 2, 4, 22, 8]

In [112]:
q = [val for val in k if val %2!=0 and val>10]
q

[67, 43, 45, 11]

In [114]:
p = []
for val in k:
    if val%2 == 0:
      p.append(val // 2)
    else:
        p.append(val * 2)
p          

[2, 14, 6, 134, 86, 17, 1, 2, 90, 11, 22, 18, 4]

In [115]:
p = [val * 2 if val %2  ==1 else val // 2 for val in k] # ye kar dena if-cond else ye wala kr dena 
p

[2, 14, 6, 134, 86, 17, 1, 2, 90, 11, 22, 18, 4]

In [116]:
p = [
    val * 2 if val % 2 ==1 else(val //2 if val < 20 else val)
    for val in k
    ]

p   


[2, 14, 6, 134, 86, 34, 1, 2, 90, 22, 22, 18, 4]

In [117]:
k

[4, 7, 3, 67, 43, 34, 2, 4, 45, 22, 11, 9, 8]

In [118]:
m = {val:val**2 for val in k if val % 2 ==0}
m

{4: 16, 34: 1156, 2: 4, 22: 484, 8: 64}

In [119]:
for i in m:
    print(i)

4
34
2
22
8


In [120]:
for key,value in m.items():
    print(key,value)
    

4 16
34 1156
2 4
22 484
8 64


In [121]:
m.items()

dict_items([(4, 16), (34, 1156), (2, 4), (22, 484), (8, 64)])

In [ ]:
# user-define functions
####################

In [126]:
def function_ka_name(): 
    '''
    blahhhhhhhhhhhhhhhhhhhhhhh
    '''
    print('ye kuch kar dega')

In [123]:
function_ka_name() # paranthesis shows that we are calling the function

ye kuch kar dega


In [124]:
function_ka_name

<function __main__.function_ka_name()>

In [127]:
help(function_ka_name)

Help on function function_ka_name in module __main__:

function_ka_name()
    blahhhhhhhhhhhhhhhhhhhhhhh



In [ ]:
# pass keyword is used to make empty string

In [128]:
def ekOr( ekval , dusriVal ):
    return ekval * dusriVal

In [129]:
ekOr(4,5)

20

In [130]:
x = ekOr(4,5)

In [ ]:
y = function_ka_name

In [131]:
print(x,y)

20 30


In [135]:
import numpy as np


ModuleNotFoundError: No module named 'numpy'

In [137]:
!python -m pip install numpy

1725822.21s - pydevd: Sending message related to process being replaced timed-out after 5 seconds



[notice] A new release of pip is available: 23.0.1 -> 23.1
[notice] To update, run: pip install --upgrade pip


In [149]:
!python3.10 -m pip install numpy

1726246.33s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.9/13.9 MB 1.5 MB/s eta 0:00:0000:0100:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [150]:
import numpy as np


In [153]:
b = np.array([[5,7,8],[7,3,4]])
b

array([[5, 7, 8],
       [7, 3, 4]])

In [154]:
K = np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
K

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [157]:
# m = np.array([[[4,8,7],[3,1,5],[6,9,13]],[[41,81,71],[31,11,51],[61,91,131]]])
m = np.array([[[4,41],[8,81],[7,71]],
[[3,31],[1,11],[5,51]],
[[6,61],[9,91],[13,131]]])
m
# [4,8,7     [41,81,71
# 3,1,5       31,11,51                        3 d array
# 6,9,13]     61,91,131]

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [158]:
m.shape

(3, 3, 2)

In [161]:
K[1][0]

9

In [162]:
K[1,0]

9

In [163]:
K[3]

array([19, 31,  8])

In [164]:
K[2,0:3:1] # third row mein 0 th column se last column tak ek ek ke indices mein ....aur ese bhi likh skte hai K[2,0:3] ..K[2,:3]...K[2,:] # subscripting

array([11, 15, 17])

In [166]:
K[0:4,1] # second column complete print krwane ke liye

array([ 8,  3, 15, 31])

In [167]:
K[:,1:2] #slicing  # 1 column se start krenge aur ek extra tak jaayenge ( result mein sirf 1 se 1 tak hi aayega iss example mein)

array([[ 8],
       [ 3],
       [15],
       [31]])

In [169]:
m[:2,-2:,:1] # isse shuru ke 2 row , 2 column aur first wala part print hoga

array([[[8],
        [7]],

       [[1],
        [5]]])

In [172]:
m[-1:,-2:,:] # isse last row ke last ke 2 column ke dono plane chahiye

array([[[  9,  91],
        [ 13, 131]]])

In [173]:
K[0,0]=55
K

array([[55,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [175]:
K[0,:]= 1,2,4
K

array([[ 1,  2,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [176]:
K[:,2]= 3,4,5,6
K

array([[ 1,  2,  3],
       [ 9,  3,  4],
       [11, 15,  5],
       [19, 31,  6]])

In [179]:
np.append(K, [[1,1,1]], axis=0) # row add hogi 0 is for row

array([[ 1,  2,  3],
       [ 9,  3,  4],
       [11, 15,  5],
       [19, 31,  6],
       [ 1,  1,  1]])

In [187]:
np.append(K, [[1],[1],[1],[1]] ,axis=1) # axis = 1 is for column

array([[ 1,  2,  3,  1],
       [ 9,  3,  4,  1],
       [11, 15,  5,  1],
       [19, 31,  6,  1]])

In [190]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [192]:
np.arange(1,11,1)  # its a range not arrange ..it gives the output in numpy array form

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [195]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [196]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [198]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
np.random.randint(1,100,3)

array([80, 86, 30])

In [2]:
import numpy as np

In [4]:
np.random.randint(1,100,[3,5])

array([[39, 58, 69, 69, 98],
       [48, 32, 73, 64, 13],
       [93, 58, 91, 80, 51]])

In [7]:
np.random.seed(1)
np.random.randint(1,100,[3,5])

array([[38, 13, 73, 10, 76],
       [ 6, 80, 65, 17,  2],
       [77, 72,  7, 26, 51]])

In [8]:
np.random.randn(3,4) # both negative and positive values in the output

array([[-0.46468632,  0.86182712, -2.65426198,  1.15226492],
       [ 0.19664341, -1.54521415, -0.08810409,  0.85223932],
       [ 0.67723401, -0.10687843,  0.72527406,  0.93488915]])

In [9]:
np.random.rand(3,4)

array([[0.8027575 , 0.09280081, 0.51815255, 0.86502025],
       [0.82914691, 0.82960336, 0.27304997, 0.0592432 ],
       [0.67052804, 0.59306552, 0.6716541 , 0.41178788]])

In [11]:
np.loadtxt('data.txt',dtype='str')

array([['this', 'is', 'a', 'new', 'file'],
       ['here', 'we', 'get', 'some', 'data']], dtype='<U4')

In [13]:
np.loadtxt('data.txt',delimiter=',')

array([[ 4.,  5.,  6.,  7.],
       [ 1.,  2.,  3.,  4.],
       [12., 13., 12., 13.]])

In [14]:
r = np.random.randint(1,1000,[3,5])
r

array([[516, 965, 793, 498,  44],
       [589,  27, 821, 337, 622],
       [884, 298, 467,  16,  65]])

In [15]:
r.sum(axis=1) # sum of the each row of array

array([2816, 2396, 1730])

In [17]:
r.argmax(axis=1) # axis=1 is for row and axis =0 is for column

array([1, 2, 0])

In [18]:
r.argmax()

1

In [19]:
r.flatten()

array([516, 965, 793, 498,  44, 589,  27, 821, 337, 622, 884, 298, 467,
        16,  65])